name: 'Setup MAUI Action'

description: 'Github Action to setup .net MAUI on any OS runner ⚙️🖥'

inputs:
    access_token:
        description: 'Github ACCESS TOKEN with access to repository url'
        required: false

runs:
  using: "composite"
  steps:

    - name: Check Runner
      run: echo 🤖 OS runner is $(uname)
      shell: bash

    - name: Install MAUI
      run: |
        dotnet workload install maui --ignore-failed-sources
      shell: bash

     
branding:
    icon: 'terminal'
    color: 'gray-dark'