name: 'Setup MAUI Action'

description: 'Github Action to setup .net MAUI on windows and osx OS runners ⚙️🖥'

inputs:
    dotnet-version: 
        description: 'Version of dotnet installation'
        required: true
        default: 7.0.x
    global-json-file:
        description: 'Optional global.json location, if your global.json isn''t located in the root of the repo.' 
        required: false
    cache:
        description: 'Optional input to enable caching of the NuGet global-packages folder'
        required: false
        default: 'false'
    cache-dependency-path:
        description: 'Used to specify the path to a dependency file: packages.lock.json. Supports wildcards or a list of file names for caching multiple dependencies.'
        required: false 

runs:
  using: "composite"
  steps:

    - name: Check Runner
      run: echo 🤖 OS runner is $(uname)
      shell: bash
    
    - uses: actions/setup-dotnet@v4
      env:
        INPUT_DOTNET_VERSION: ${{ inputs.dotnet-version }}
        INPUT_JSON_FILE: ${{ inputs.global-json-file }}
        INPUT_CACHE: ${{ inputs.cache }}
        INPUT_CACHE_DEP: ${{ inputs.cache-dependency-path }}  
      with:
        dotnet-version: ${{ env.INPUT_DOTNET_VERSION }}
        global-json-file: ${{ env.INPUT_JSON_FILE }}
        cache: ${{ env.INPUT_CACHE }}
        cache-dependency-path: ${{ env.INPUT_CACHE }}
        
    - name: Setup dotnet
      run: |
        dotnet --version
      shell: bash
    
    - name: Install MAUI
      run: |
        dotnet workload install maui --ignore-failed-sources
      shell: bash

     
branding:
    icon: 'terminal'
    color: 'gray-dark'