name: release .nupkg's

on:
  push:
    tags: 
        '*' 
permissions:
  contents: read
 
jobs:
  publish:
    runs-on: macos-13
    name: publish
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
            draft: false
            prerelease: false
            release_name: ${{ github.ref }}
            tag_name: ${{ github.ref }}
            body_path: CHANGELOG.md
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}