name: Action test on Ubuntu

on:
  push:
  workflow_dispatch:

jobs:

  public-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: weslleymurdock/setup-maui-action@main
      
      - name: Create classlib
        run: dotnet new mauilib -n MauiLibDemo

      - name: Create classlib
        run: dotnet build MauiLibDemo/MauiLibDemo.csproj

  