name: Action test on Windows

on:
  push:
  workflow_dispatch:

jobs:

  public-repo:
    runs-on: windows-latest
    steps: 
      - uses: weslleymurdock/setup-maui-action@main
      with:
        dotnet-version: 8.0.x  
      
      - name: Create classlib
        run: dotnet new mauilib -n MauiLibDemo

      - name: Build classlib
        run: dotnet build MauiLibDemo/MauiLibDemo.csproj

  